//go:build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
)

var (
	Output = flag.String("o", "const.go", "output path")
)

func main() {
	flag.Parse()

	if err := run(flag.Args()...); err != nil {
		fmt.Fprintf(os.Stderr, "error: generate constants: %v\n", err)
		os.Exit(1)
	}
}

func run(src ...string) error {
	var b strings.Builder
	b.WriteString("// Code generated by constgen; DO NOT EDIT.\n\n")
	b.WriteString("package internal\n")
	seen := map[string]struct{}{}
	for _, name := range src {
		buf, err := os.ReadFile(name)
		if err != nil {
			return err
		}

		var (
			inside bool
			last   string
			idx    int
		)
		for line := range bytes.Lines(buf) {
			// this is very rudimentary and doesn't check much, but we only need
			// it to work on known inputs

			line, _, _ := strings.Cut(strings.TrimSpace(string(line)), "//")

			if strings.HasPrefix(line, "#") {
				continue
			}

			if !inside {
				if strings.HasPrefix(line, "typedef enum {") {
					b.WriteString("\nconst (\n")
					inside = true
					last = ""
				}
				continue
			}

			if strings.HasPrefix(line, "}") {
				b.WriteString(")\n")
				inside = false
				continue
			}

			name, val, ok := strings.Cut(strings.Trim(line, ","), "=")
			if !ok {
				if last == "" {
					return fmt.Errorf("no value before %q", line)
				}
				idx++
				fmt.Fprintf(&b, "%s = %s + %d\n", name, last, idx)
				continue
			}

			name = strings.TrimSpace(name)
			if _, ok := seen[name]; ok {
				return fmt.Errorf("duplicate %q", name)
			}
			seen[name] = struct{}{}

			val = strings.TrimSpace(val)
			val = strings.TrimRight(val, "u")
			_, err := strconv.ParseInt(val, 0, 0)
			if err != nil {
				return fmt.Errorf("invalid %q %q: %w", name, val, err)
			}
			fmt.Fprintf(&b, "%s = %s\n", name, val)

			last = val
			idx = 0
		}
	}
	if out, err := format.Source([]byte(b.String())); err != nil {
		return fmt.Errorf("format: %w", err)
	} else if err := os.WriteFile(*Output, out, 0644); err != nil {
		return err
	}
	return nil
}
